"""add teacher recommendation table

Revision ID: 5fba087aa55a
Revises: k1f2g3h4i5j6
Create Date: 2026-05-13 07:50:42.746358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5fba087aa55a'
down_revision = 'k1f2g3h4i5j6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacherrecommendation',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_lesson_group_id'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_scheduled_at'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_series_id'), table_name='lesson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lesson_series_id'), 'lesson', ['series_id'], unique=False)
    op.create_index(op.f('ix_lesson_scheduled_at'), 'lesson', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_lesson_group_id'), 'lesson', ['group_id'], unique=False)
    op.drop_table('teacherrecommendation')
    # ### end Alembic commands ###
